export const availableFacilities = [
  { id: "WIFI", name: "WiFi" },
  { id: "TV", name: "TV" },
  { id: "AC", name: "AC" },
  { id: "ROOM_SERVICES", name: "Layanan Kamar" },
  { id: "MINI_BAR", name: "Mini Bar" },
  { id: "LAUNDRY", name: "Laundry" },
  { id: "SETRIKA", name: "Setrika" },
  { id: "ALAT_PEMADAM_API", name: "Alat Pemadam Api" },
  { id: "MICROWAVE", name: "Microwave" },
  { id: "KULKAS", name: "Kulkas" },
  { id: "RUANG_KERJA_KHUSUS", name: "Ruang kerja khusus" },
  { id: "KITCHEN", name: "Dapur" },
  { id: "HEATING", name: "Pemanas Ruangan" },
  { id: "AIR_PURIFIER", name: "Pembersih Udara" },
  { id: "SAFE", name: "Brankas" },
  { id: "BATHROBES", name: "Jubah Mandi" },
  { id: "TEA_COFFEE_MAKER", name: "Pembuat Teh/Kopi" },
  { id: "BALCONY", name: "Balkon" },
  { id: "BATHTUB", name: "Bak Mandi" },
  { id: "JACUZZI", name: "Jacuzzi" },
  { id: "PRIVATE_POOL", name: "Kolam Privat" },
];
